# Generated by Django 3.2.4 on 2021-06-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Accnumber', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.BigIntegerField()),
                ('reciever', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
            ],
        ),
    ]
