# Generated by Django 3.2.4 on 2021-06-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Accnumber',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
